In [1]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [2]:
from tensorflow.keras.layers import TextVectorization
# Just a simple test
sentences = [
    "I like eggs and ham.",
    "I love chocolate and bunnies.",
    "I hate onions."
]

In [3]:
MAX_VOCAB_SIZE = 20000
# commented out default values
vectorize_layer = TextVectorization(
  max_tokens=MAX_VOCAB_SIZE,
  # standardize="lower_and_strip_punctuation",
  # split="whitespace",
  # output_mode='int',
)

In [4]:
vectorize_layer.adapt(sentences)
sequences = vectorize_layer(sentences)
print(sequences)

tf.Tensor(
[[ 2  6  9  3  8]
 [ 2  5 10  3 11]
 [ 2  7  4  0  0]], shape=(3, 5), dtype=int64)


In [5]:
# NOTE: '' is a placeholder for pad token
vectorize_layer.get_vocabulary()

['',
 '[UNK]',
 np.str_('i'),
 np.str_('and'),
 np.str_('onions'),
 np.str_('love'),
 np.str_('like'),
 np.str_('hate'),
 np.str_('ham'),
 np.str_('eggs'),
 np.str_('chocolate'),
 np.str_('bunnies')]

In [6]:
# How to get the word to index mapping?
# It's not included, but it's redundant since it can be derived
word2idx = {v: k for k, v in enumerate(vectorize_layer.get_vocabulary())}
print(word2idx)

{'': 0, '[UNK]': 1, np.str_('i'): 2, np.str_('and'): 3, np.str_('onions'): 4, np.str_('love'): 5, np.str_('like'): 6, np.str_('hate'): 7, np.str_('ham'): 8, np.str_('eggs'): 9, np.str_('chocolate'): 10, np.str_('bunnies'): 11}


In [7]:
# truncatation
vectorize_layer_truncated = TextVectorization(
  max_tokens=MAX_VOCAB_SIZE,
  output_sequence_length=3,
)

# fit
vectorize_layer_truncated.adapt(sentences)

# predict
sequences = vectorize_layer_truncated(sentences)
print(sequences)

tf.Tensor(
[[ 2  6  9]
 [ 2  5 10]
 [ 2  7  4]], shape=(3, 3), dtype=int64)


In [8]:
# ragged (no padding) (TF backend only)
vectorize_layer_ragged = TextVectorization(
  max_tokens=MAX_VOCAB_SIZE,
  ragged=True,
)

# fit
vectorize_layer_ragged.adapt(sentences)

# predict
sequences = vectorize_layer_ragged(sentences)
print(sequences)

<tf.RaggedTensor [[2, 6, 9, 3, 8], [2, 5, 10, 3, 11], [2, 7, 4]]>


In [9]:
# pad at front instead of back
# not supported in TextVectorization layer itself
from tensorflow.keras.utils import pad_sequences

# defaults:
# tf.keras.utils.pad_sequences(
#     sequences,
#     maxlen=None,
#     dtype='int32',
#     padding='pre',
#     truncating='pre',
#     value=0.0
# )

padded = pad_sequences(sequences.to_list())
print(padded)

[[ 2  6  9  3  8]
 [ 2  5 10  3 11]
 [ 0  0  2  7  4]]
